// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My_Application.Database;

namespace My_Application.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("My_Application.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("417ce6e2-e563-43ce-8dfc-7d54e032b83e"),
                            Email = "TempEmail 1 @hotmail.com",
                            FirstName = " FirstName 1 ",
                            IsAdmin = false,
                            LastName = " LastName 1 ",
                            Password = "! 1 ! Password",
                            UserId = 1,
                            Username = "Username 1 "
                        },
                        new
                        {
                            Id = new Guid("d49c366f-4e10-4dd2-8662-d3f935f888af"),
                            Email = "TempEmail 2 @hotmail.com",
                            FirstName = " FirstName 2 ",
                            IsAdmin = false,
                            LastName = " LastName 2 ",
                            Password = "! 2 ! Password",
                            UserId = 2,
                            Username = "Username 2 "
                        },
                        new
                        {
                            Id = new Guid("07380cb6-6c13-419c-9e69-c603c8f6079e"),
                            Email = "TempEmail 3 @hotmail.com",
                            FirstName = " FirstName 3 ",
                            IsAdmin = false,
                            LastName = " LastName 3 ",
                            Password = "! 3 ! Password",
                            UserId = 3,
                            Username = "Username 3 "
                        },
                        new
                        {
                            Id = new Guid("8a43ba80-19a5-4c17-938a-30905a327cae"),
                            Email = "TempEmail 4 @hotmail.com",
                            FirstName = " FirstName 4 ",
                            IsAdmin = false,
                            LastName = " LastName 4 ",
                            Password = "! 4 ! Password",
                            UserId = 4,
                            Username = "Username 4 "
                        },
                        new
                        {
                            Id = new Guid("4126e767-de14-449a-9384-d43627203f3e"),
                            Email = "TempEmail 5 @hotmail.com",
                            FirstName = " FirstName 5 ",
                            IsAdmin = false,
                            LastName = " LastName 5 ",
                            Password = "! 5 ! Password",
                            UserId = 5,
                            Username = "Username 5 "
                        },
                        new
                        {
                            Id = new Guid("667c8991-ba18-4c0f-be1f-95e0d9ffb468"),
                            Email = "TempEmail 6 @hotmail.com",
                            FirstName = " FirstName 6 ",
                            IsAdmin = false,
                            LastName = " LastName 6 ",
                            Password = "! 6 ! Password",
                            UserId = 6,
                            Username = "Username 6 "
                        },
                        new
                        {
                            Id = new Guid("db61264f-5c8d-4fa6-b8d9-44fd803516e1"),
                            Email = "TempEmail 7 @hotmail.com",
                            FirstName = " FirstName 7 ",
                            IsAdmin = false,
                            LastName = " LastName 7 ",
                            Password = "! 7 ! Password",
                            UserId = 7,
                            Username = "Username 7 "
                        },
                        new
                        {
                            Id = new Guid("0085a643-3561-4ca5-b8fe-c08ad52686f0"),
                            Email = "TempEmail 8 @hotmail.com",
                            FirstName = " FirstName 8 ",
                            IsAdmin = false,
                            LastName = " LastName 8 ",
                            Password = "! 8 ! Password",
                            UserId = 8,
                            Username = "Username 8 "
                        },
                        new
                        {
                            Id = new Guid("74e03aec-e790-4826-b237-023ffc114201"),
                            Email = "TempEmail 9 @hotmail.com",
                            FirstName = " FirstName 9 ",
                            IsAdmin = false,
                            LastName = " LastName 9 ",
                            Password = "! 9 ! Password",
                            UserId = 9,
                            Username = "Username 9 "
                        },
                        new
                        {
                            Id = new Guid("241398fe-62b3-47a2-a0d9-c85bba3665ec"),
                            Email = "TempEmail 10 @hotmail.com",
                            FirstName = " FirstName 10 ",
                            IsAdmin = false,
                            LastName = " LastName 10 ",
                            Password = "! 10 ! Password",
                            UserId = 10,
                            Username = "Username 10 "
                        },
                        new
                        {
                            Id = new Guid("0979160c-95c3-401a-ac29-8c1c36a0cdb7"),
                            Email = "TempEmail 11 @hotmail.com",
                            FirstName = " FirstName 11 ",
                            IsAdmin = false,
                            LastName = " LastName 11 ",
                            Password = "! 11 ! Password",
                            UserId = 11,
                            Username = "Username 11 "
                        },
                        new
                        {
                            Id = new Guid("a2625a33-65b7-4d29-9a64-f5c6f6c2a4ae"),
                            Email = "TempEmail 12 @hotmail.com",
                            FirstName = " FirstName 12 ",
                            IsAdmin = false,
                            LastName = " LastName 12 ",
                            Password = "! 12 ! Password",
                            UserId = 12,
                            Username = "Username 12 "
                        },
                        new
                        {
                            Id = new Guid("b08ad8ed-11a2-40d6-9234-e46053019335"),
                            Email = "TempEmail 13 @hotmail.com",
                            FirstName = " FirstName 13 ",
                            IsAdmin = false,
                            LastName = " LastName 13 ",
                            Password = "! 13 ! Password",
                            UserId = 13,
                            Username = "Username 13 "
                        },
                        new
                        {
                            Id = new Guid("f79a2c4d-904b-4410-b6ce-5e5ea9a3e0c2"),
                            Email = "TempEmail 14 @hotmail.com",
                            FirstName = " FirstName 14 ",
                            IsAdmin = false,
                            LastName = " LastName 14 ",
                            Password = "! 14 ! Password",
                            UserId = 14,
                            Username = "Username 14 "
                        },
                        new
                        {
                            Id = new Guid("d51d2b52-2598-4f1a-ad80-4f24141ea571"),
                            Email = "TempEmail 15 @hotmail.com",
                            FirstName = " FirstName 15 ",
                            IsAdmin = false,
                            LastName = " LastName 15 ",
                            Password = "! 15 ! Password",
                            UserId = 15,
                            Username = "Username 15 "
                        },
                        new
                        {
                            Id = new Guid("b06563d4-3663-4108-9ac7-08af1c080bc0"),
                            Email = "TempEmail 16 @hotmail.com",
                            FirstName = " FirstName 16 ",
                            IsAdmin = false,
                            LastName = " LastName 16 ",
                            Password = "! 16 ! Password",
                            UserId = 16,
                            Username = "Username 16 "
                        },
                        new
                        {
                            Id = new Guid("33bec53b-6b25-4335-af6f-9b031e959e33"),
                            Email = "TempEmail 17 @hotmail.com",
                            FirstName = " FirstName 17 ",
                            IsAdmin = false,
                            LastName = " LastName 17 ",
                            Password = "! 17 ! Password",
                            UserId = 17,
                            Username = "Username 17 "
                        },
                        new
                        {
                            Id = new Guid("7d555476-18cd-42b4-908f-048830eaf412"),
                            Email = "TempEmail 18 @hotmail.com",
                            FirstName = " FirstName 18 ",
                            IsAdmin = false,
                            LastName = " LastName 18 ",
                            Password = "! 18 ! Password",
                            UserId = 18,
                            Username = "Username 18 "
                        },
                        new
                        {
                            Id = new Guid("dc6548a9-b9f2-4add-93d3-68ae6d260bed"),
                            Email = "TempEmail 19 @hotmail.com",
                            FirstName = " FirstName 19 ",
                            IsAdmin = false,
                            LastName = " LastName 19 ",
                            Password = "! 19 ! Password",
                            UserId = 19,
                            Username = "Username 19 "
                        },
                        new
                        {
                            Id = new Guid("64256e3b-ddc9-4cd0-9fa7-3701d8a770d9"),
                            Email = "TempEmail 20 @hotmail.com",
                            FirstName = " FirstName 20 ",
                            IsAdmin = false,
                            LastName = " LastName 20 ",
                            Password = "! 20 ! Password",
                            UserId = 20,
                            Username = "Username 20 "
                        },
                        new
                        {
                            Id = new Guid("4fbe3f6f-f17f-467f-902e-8bc8bd4b2560"),
                            Email = "TempEmail 21 @hotmail.com",
                            FirstName = " FirstName 21 ",
                            IsAdmin = false,
                            LastName = " LastName 21 ",
                            Password = "! 21 ! Password",
                            UserId = 21,
                            Username = "Username 21 "
                        },
                        new
                        {
                            Id = new Guid("e49988b1-be4e-4c0b-b641-4de06f515931"),
                            Email = "TempEmail 22 @hotmail.com",
                            FirstName = " FirstName 22 ",
                            IsAdmin = false,
                            LastName = " LastName 22 ",
                            Password = "! 22 ! Password",
                            UserId = 22,
                            Username = "Username 22 "
                        },
                        new
                        {
                            Id = new Guid("f5ca4584-c666-4154-a5c4-485fc28c06fc"),
                            Email = "TempEmail 23 @hotmail.com",
                            FirstName = " FirstName 23 ",
                            IsAdmin = false,
                            LastName = " LastName 23 ",
                            Password = "! 23 ! Password",
                            UserId = 23,
                            Username = "Username 23 "
                        },
                        new
                        {
                            Id = new Guid("0715b3b3-83b9-4769-8352-9fa64a0c7b26"),
                            Email = "TempEmail 24 @hotmail.com",
                            FirstName = " FirstName 24 ",
                            IsAdmin = false,
                            LastName = " LastName 24 ",
                            Password = "! 24 ! Password",
                            UserId = 24,
                            Username = "Username 24 "
                        },
                        new
                        {
                            Id = new Guid("3e8bf9ed-99b2-41dd-a3ca-b9ce49865f76"),
                            Email = "TempEmail 25 @hotmail.com",
                            FirstName = " FirstName 25 ",
                            IsAdmin = false,
                            LastName = " LastName 25 ",
                            Password = "! 25 ! Password",
                            UserId = 25,
                            Username = "Username 25 "
                        },
                        new
                        {
                            Id = new Guid("6ea4f61e-2921-42bd-a3e2-823741dd2770"),
                            Email = "TempEmail 26 @hotmail.com",
                            FirstName = " FirstName 26 ",
                            IsAdmin = false,
                            LastName = " LastName 26 ",
                            Password = "! 26 ! Password",
                            UserId = 26,
                            Username = "Username 26 "
                        },
                        new
                        {
                            Id = new Guid("4314c135-84f6-460d-a1a2-9d1360fa40c0"),
                            Email = "TempEmail 27 @hotmail.com",
                            FirstName = " FirstName 27 ",
                            IsAdmin = false,
                            LastName = " LastName 27 ",
                            Password = "! 27 ! Password",
                            UserId = 27,
                            Username = "Username 27 "
                        },
                        new
                        {
                            Id = new Guid("18a5433a-6d02-46e9-bddd-3c34ef4816b3"),
                            Email = "TempEmail 28 @hotmail.com",
                            FirstName = " FirstName 28 ",
                            IsAdmin = false,
                            LastName = " LastName 28 ",
                            Password = "! 28 ! Password",
                            UserId = 28,
                            Username = "Username 28 "
                        },
                        new
                        {
                            Id = new Guid("f150fcd0-8582-43e3-8646-331c011d7368"),
                            Email = "TempEmail 29 @hotmail.com",
                            FirstName = " FirstName 29 ",
                            IsAdmin = false,
                            LastName = " LastName 29 ",
                            Password = "! 29 ! Password",
                            UserId = 29,
                            Username = "Username 29 "
                        },
                        new
                        {
                            Id = new Guid("e939d6e6-47f7-405f-9602-4551c370d215"),
                            Email = "TempEmail 30 @hotmail.com",
                            FirstName = " FirstName 30 ",
                            IsAdmin = false,
                            LastName = " LastName 30 ",
                            Password = "! 30 ! Password",
                            UserId = 30,
                            Username = "Username 30 "
                        },
                        new
                        {
                            Id = new Guid("d191aba7-827a-4c48-b4df-7e71ee26826e"),
                            Email = "TempEmail 31 @hotmail.com",
                            FirstName = " FirstName 31 ",
                            IsAdmin = false,
                            LastName = " LastName 31 ",
                            Password = "! 31 ! Password",
                            UserId = 31,
                            Username = "Username 31 "
                        },
                        new
                        {
                            Id = new Guid("49022534-4320-44af-a40c-eaf0b5a48a34"),
                            Email = "TempEmail 32 @hotmail.com",
                            FirstName = " FirstName 32 ",
                            IsAdmin = false,
                            LastName = " LastName 32 ",
                            Password = "! 32 ! Password",
                            UserId = 32,
                            Username = "Username 32 "
                        },
                        new
                        {
                            Id = new Guid("ae7a85c6-1845-4c45-a89c-5c5887a31e47"),
                            Email = "TempEmail 33 @hotmail.com",
                            FirstName = " FirstName 33 ",
                            IsAdmin = false,
                            LastName = " LastName 33 ",
                            Password = "! 33 ! Password",
                            UserId = 33,
                            Username = "Username 33 "
                        },
                        new
                        {
                            Id = new Guid("0262d37d-9124-46e5-a7c0-cd812e664f72"),
                            Email = "TempEmail 34 @hotmail.com",
                            FirstName = " FirstName 34 ",
                            IsAdmin = false,
                            LastName = " LastName 34 ",
                            Password = "! 34 ! Password",
                            UserId = 34,
                            Username = "Username 34 "
                        },
                        new
                        {
                            Id = new Guid("e87b8d27-0ef7-41fb-b815-a248087c84c6"),
                            Email = "TempEmail 35 @hotmail.com",
                            FirstName = " FirstName 35 ",
                            IsAdmin = false,
                            LastName = " LastName 35 ",
                            Password = "! 35 ! Password",
                            UserId = 35,
                            Username = "Username 35 "
                        },
                        new
                        {
                            Id = new Guid("81de4ed0-fa61-4fde-a9c5-077ac2c6f9e3"),
                            Email = "TempEmail 36 @hotmail.com",
                            FirstName = " FirstName 36 ",
                            IsAdmin = false,
                            LastName = " LastName 36 ",
                            Password = "! 36 ! Password",
                            UserId = 36,
                            Username = "Username 36 "
                        },
                        new
                        {
                            Id = new Guid("b16fbe2b-adf9-425d-82ea-773650526604"),
                            Email = "TempEmail 37 @hotmail.com",
                            FirstName = " FirstName 37 ",
                            IsAdmin = false,
                            LastName = " LastName 37 ",
                            Password = "! 37 ! Password",
                            UserId = 37,
                            Username = "Username 37 "
                        },
                        new
                        {
                            Id = new Guid("7568d273-d856-45de-b0f0-854a3e0d0af7"),
                            Email = "TempEmail 38 @hotmail.com",
                            FirstName = " FirstName 38 ",
                            IsAdmin = false,
                            LastName = " LastName 38 ",
                            Password = "! 38 ! Password",
                            UserId = 38,
                            Username = "Username 38 "
                        },
                        new
                        {
                            Id = new Guid("d0a67dfb-a0c1-4189-be40-3ce12fc93295"),
                            Email = "TempEmail 39 @hotmail.com",
                            FirstName = " FirstName 39 ",
                            IsAdmin = false,
                            LastName = " LastName 39 ",
                            Password = "! 39 ! Password",
                            UserId = 39,
                            Username = "Username 39 "
                        },
                        new
                        {
                            Id = new Guid("126d12f6-5ff3-4978-98ba-2a27c287d1cf"),
                            Email = "TempEmail 40 @hotmail.com",
                            FirstName = " FirstName 40 ",
                            IsAdmin = false,
                            LastName = " LastName 40 ",
                            Password = "! 40 ! Password",
                            UserId = 40,
                            Username = "Username 40 "
                        },
                        new
                        {
                            Id = new Guid("869dc515-666a-4557-82c8-56d8b93b4546"),
                            Email = "TempEmail 41 @hotmail.com",
                            FirstName = " FirstName 41 ",
                            IsAdmin = false,
                            LastName = " LastName 41 ",
                            Password = "! 41 ! Password",
                            UserId = 41,
                            Username = "Username 41 "
                        },
                        new
                        {
                            Id = new Guid("4b825af9-b9ce-4cf8-96d4-22834c0692f9"),
                            Email = "TempEmail 42 @hotmail.com",
                            FirstName = " FirstName 42 ",
                            IsAdmin = false,
                            LastName = " LastName 42 ",
                            Password = "! 42 ! Password",
                            UserId = 42,
                            Username = "Username 42 "
                        },
                        new
                        {
                            Id = new Guid("b0189d88-0a98-4fce-b631-b5e4e4206765"),
                            Email = "TempEmail 43 @hotmail.com",
                            FirstName = " FirstName 43 ",
                            IsAdmin = false,
                            LastName = " LastName 43 ",
                            Password = "! 43 ! Password",
                            UserId = 43,
                            Username = "Username 43 "
                        },
                        new
                        {
                            Id = new Guid("ba093501-3f30-435e-81b6-456e177fb2eb"),
                            Email = "TempEmail 44 @hotmail.com",
                            FirstName = " FirstName 44 ",
                            IsAdmin = false,
                            LastName = " LastName 44 ",
                            Password = "! 44 ! Password",
                            UserId = 44,
                            Username = "Username 44 "
                        },
                        new
                        {
                            Id = new Guid("e2b05840-7bb4-4699-9713-5438c2dd0909"),
                            Email = "TempEmail 45 @hotmail.com",
                            FirstName = " FirstName 45 ",
                            IsAdmin = false,
                            LastName = " LastName 45 ",
                            Password = "! 45 ! Password",
                            UserId = 45,
                            Username = "Username 45 "
                        },
                        new
                        {
                            Id = new Guid("2409f541-e972-4e0b-8857-99656410d33c"),
                            Email = "TempEmail 46 @hotmail.com",
                            FirstName = " FirstName 46 ",
                            IsAdmin = false,
                            LastName = " LastName 46 ",
                            Password = "! 46 ! Password",
                            UserId = 46,
                            Username = "Username 46 "
                        },
                        new
                        {
                            Id = new Guid("559d455f-27a0-432f-bb1b-82a36847b51d"),
                            Email = "TempEmail 47 @hotmail.com",
                            FirstName = " FirstName 47 ",
                            IsAdmin = false,
                            LastName = " LastName 47 ",
                            Password = "! 47 ! Password",
                            UserId = 47,
                            Username = "Username 47 "
                        },
                        new
                        {
                            Id = new Guid("f498973a-e29b-4809-95ff-681510d65dec"),
                            Email = "TempEmail 48 @hotmail.com",
                            FirstName = " FirstName 48 ",
                            IsAdmin = false,
                            LastName = " LastName 48 ",
                            Password = "! 48 ! Password",
                            UserId = 48,
                            Username = "Username 48 "
                        },
                        new
                        {
                            Id = new Guid("d30dc3e2-601a-4761-8d9b-f7ef2e85af9a"),
                            Email = "TempEmail 49 @hotmail.com",
                            FirstName = " FirstName 49 ",
                            IsAdmin = false,
                            LastName = " LastName 49 ",
                            Password = "! 49 ! Password",
                            UserId = 49,
                            Username = "Username 49 "
                        },
                        new
                        {
                            Id = new Guid("8f5d8b3d-26b7-4536-b44a-32b0181f2b82"),
                            Email = "TempEmail 50 @hotmail.com",
                            FirstName = " FirstName 50 ",
                            IsAdmin = false,
                            LastName = " LastName 50 ",
                            Password = "! 50 ! Password",
                            UserId = 50,
                            Username = "Username 50 "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
